s = set()

n = int(input("Enter the Num1: "))
s.add(n)
n = int(input("Enter the Num2: "))
s.add(n)
n = int(input("Enter the Num3: "))
s.add(n)
n = int(input("Enter the Num4: "))
s.add(n)
n = int(input("Enter the Num5: "))
s.add(n)
n = int(input("Enter the Num6: "))
s.add(n)
n = int(input("Enter the Num7: "))
s.add(n)
n = int(input("Enter the Num8: "))
s.add(n)

print(s)